services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "$HOME/data/redis:/data"
    command: redis-server --requirepass 123456
  
  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    user: root
    ports:
      - "9010:9000"   # S3 API 对外端口
      - "9011:9001"   # 控制台对外端口
    environment:
      RUSTFS_CONSOLE_ENABLE: true
      # CORS 设置，控制台与 S3 API 都放开来源
      RUSTFS_CORS_ALLOWED_ORIGINS: "*"
      RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS: "*"
      # 访问密钥（生产环境请修改为强密码）
      RUSTFS_ACCESS_KEY: MarkusPersad
      RUSTFS_SECRET_KEY: "12345678"
      RUSTFS_REGION: cn-north-1
      # 日志级别
      RUSTFS_LOG_LEVEL: info

    volumes:
      # 存储数据卷
      - $HOME/data/rustfs:/data
      # 日志目录
      - $HOME/data/logs/rustfs:/app/logs

  geo-data:
    image: kartoza/postgis
    container_name: geo-data
    volumes:
      - $HOME/data/postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=geo_data,postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - ALLOW_IP_RANGE=0.0.0.0/0
    restart: on-failure
    healthcheck:
      test: "pg_isready -h 127.0.0.1 -U postgres"
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m
  
  geoserver:
    image: kartoza/geoserver
    container_name: geoserver
    environment:
      - SAMPLE_DATA=true
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - FOOTPRINTS_DATA_DIR=/opt/footprints_dir
      - FONTS_DIR=/opt/fonts
      - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/gwc
      - GEOSERVER_ADMIN_PASSWORD=123456
      - GEOSERVER_ADMIN_USER=admin
      - INITIAL_MEMORY=2G
      - MAXIMUM_MEMORY=4G
      - ENCODING='UTF8'
      - LOGIN_STATUS=on
      - REQUEST_TIMEOUT=60
      - PARALLEL_REQUEST=100
      - GETMAP=10
      - REQUEST_EXCEL=4
      - SINGLE_USER=6
      - GWC_REQUEST=16
      - WPS_REQUEST=1000/d;30s
      - POSTGRES_JNDI=TRUE 
      - DB_BACKEND=POSTGRES               
      - HOST=geo-data                          
      - POSTGRES_PORT=5432                
      - POSTGRES_DB=geo_data                   
      - POSTGRES_USER=postgres  
      - POSTGRES_PASS=123456                        
      - POSTGRES_SCHEMA=public           
      - DISK_QUOTA_SIZE=5
    ports:
      - "8082:8080"
    volumes:
      - $HOME/data/geoserver/data_dir:/opt/geoserver/data_dir
      - $HOME/data/geoserver/gwc:/opt/geoserver/gwc
      - $HOME/data/geoserver/settings:/settings
    depends_on:
        geo-data:
          condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null -u $${GEOSERVER_ADMIN_USER}:$${GEOSERVER_ADMIN_PASSWORD} http://localhost:8080/geoserver/rest/about/version.xml" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m